<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <IsAspireSharedProject>false</IsAspireSharedProject>
    <UserSecretsId>BlobToCosmosFunction.AppHost</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="README.md" />
  </ItemGroup>

  <ItemGroup>
    <!-- Aspire.Hosting is included by Aspire.AppHost.Sdk -->
    <PackageReference Include="Aspire.Hosting.Azure.CosmosDB" Version="13.1.0" />
    <PackageReference Include="Aspire.Hosting.Azure.Functions" Version="13.1.0" />
    <PackageReference Include="Aspire.Hosting.Azure.Storage" Version="13.1.0" />
  </ItemGroup>

</Project>
